### ISSUE TITLE
MSP430透過SPI讀取MPU9250

### ISSUE THREAD

**Issue by YanJenHuang** [KitSprout/SmartIMU#9]
嗨你好，
我目前是透過MSP430F5438A的SPI來讀取MPU9250的資料，因為才剛接觸MSP430，所以對一些設定方式都沒還不太熟悉。
目前我先嘗試讀取MPU9250的WHO AM I(0x75)的數值，以下是我的流程及code：
1. SPI_INIT()
2. Select slave device(將 MPU9250 CS 拉low)
3. 在UCA0TXBUF = 0x75 | READ_FLAG
4. 讀取 UCA0RXBUF的值

`int main(void) 
{
    WDTCTL = WDTPW | WDTHOLD;   // Stop watchdog timer

```
Chip_Selector_Init(BIT2);
SPI_Init();

Select_Device(BIT2);

while (!(UCA0IFG & UCTXIFG));
UCA0TXBUF = 0x75 | READ_FLAG;
while(!(UCA0IFG & UCRXIFG));
received_ch = UCA0RXBUF;

return 0;
```

}`

`void SPI_Init()
{
    // P3.0 UCA0CLK -> SCL
    // P3.4 UCA0SIMO -> SDA
    // P3.5 UCA0SOMI -> AD0
    P3SEL |= BIT0 + BIT4 + BIT5;

```
UCA0CTL1 = UCSWRST;
UCA0CTL0 |= UCCKPH + UCMSB + UCMST + UCSYNC; // 3-pin, 8-bit SPI master
UCA0CTL1 |= UCSSEL_2; // SMCLK
UCA0BR0 |= 0x02; // /2
UCA0BR1 = 0; //
UCA0MCTL = 0; // No modulation
UCA0CTL1 &= ~UCSWRST; // **Initialize USCI state machine** //
```

}`

我這RXBUF始終讀取到0xFF，目前我猜測會不會是我沒有設定clock frequency，我看MPU9250的data sheet p.36寫 The maximum frequency of SCLK is 1MHz
![1](https://cloud.githubusercontent.com/assets/13307758/15736270/26e4469a-28d1-11e6-9f81-81339e093c57.png)

p.5 寫 the sensor and interrupt registers may be read using SPI at 20MHz.
![2](https://cloud.githubusercontent.com/assets/13307758/15736272/29e0206c-28d1-11e6-8340-d2e8a3109761.png)

所以感到很疑惑，MPU9250的clock frequecy 最大可以到多少，會不會是因為我沒有設定clock而導致無法讀取到WHO AM I?

**Comment by Hom-Wang** [comment]
依 datasheet 的說明，讀最大速度較高，寫最大速度較低

![13344534_275807652755271_2328767909076338218_n](https://cloud.githubusercontent.com/assets/4789358/15745953/047ea86c-2907-11e6-9561-482ec9d97f11.jpg)

始終讀取到 0xFF 通常表示你的 SPI 通訊有問題，可能是 MSP430 的相關設定錯誤，也可能是線接錯或接反，MPU9250 的 WHO_AM_I 暫存器是固定數值的，不會因為其他 9250 的暫存器沒設定好就無法讀取出或讀錯，建議可以將 CS, SCK, SDO, SDI 鉤上探棒，透過示波器觀察波形來確定傳輸是否無誤
